### ISSUE TITLE
Column reference ambiguous

### ISSUE THREAD

**Issue by leonel1524** [erpcya/adempiere-gRPC-Server#5]
Hello everyone, there is an ambiguity error on the server when trying to load some windows.
The error is caused by the following SQL query: 

> SELECT COUNT(*)  FROM C_Order AS C_Order LEFT JOIN C_DocType AS C_DocTypeTarget_ID_C_DocType ON(C_DocTypeTarget_ID_C_DocType.C_DocType_ID = C_Order.C_DocTypeTarget_ID) LEFT JOIN C_BPartner AS Bill_BPartner_ID_C_BPartner ON(Bill_BPartner_ID_C_BPartner.C_BPartner_ID = C_Order.Bill_BPartner_ID) LEFT JOIN C_BPartner_Location AS Bill_Location_ID_C_BPartner_Location ON(Bill_Location_ID_C_BPartner_Location.C_BPartner_Location_ID = C_Order.Bill_Location_ID) LEFT JOIN AD_User AS Bill_User_ID_AD_User ON(Bill_User_ID_AD_User.AD_User_ID = C_Order.Bill_User_ID) LEFT JOIN AD_Ref_List AS DeliveryRule_AD_Ref_List ON(DeliveryRule_AD_Ref_List.Value = C_Order.DeliveryRule AND DeliveryRule_AD_Ref_List.AD_Reference_ID = 151) LEFT JOIN AD_Ref_List AS PriorityRule_AD_Ref_List ON(PriorityRule_AD_Ref_List.Value = C_Order.PriorityRule AND PriorityRule_AD_Ref_List.AD_Reference_ID = 154) LEFT JOIN C_BPartner AS DropShip_BPartner_ID_C_BPartner ON(DropShip_BPartner_ID_C_BPartner.C_BPartner_ID = C_Order.DropShip_BPartner_ID) LEFT JOIN C_BPartner_Location AS DropShip_Location_ID_C_BPartner_Location ON(DropShip_Location_ID_C_BPartner_Location.C_BPartner_Location_ID = C_Order.DropShip_Location_ID) LEFT JOIN AD_User AS DropShip_User_ID_AD_User ON(DropShip_User_ID_AD_User.AD_User_ID = C_Order.DropShip_User_ID) LEFT JOIN AD_Ref_List AS DeliveryViaRule_AD_Ref_List ON(DeliveryViaRule_AD_Ref_List.Value = C_Order.DeliveryViaRule AND DeliveryViaRule_AD_Ref_List.AD_Reference_ID = 152) LEFT JOIN AD_Ref_List AS FreightCostRule_AD_Ref_List ON(FreightCostRule_AD_Ref_List.Value = C_Order.FreightCostRule AND FreightCostRule_AD_Ref_List.AD_Reference_ID = 153) LEFT JOIN AD_Ref_List AS InvoiceRule_AD_Ref_List ON(InvoiceRule_AD_Ref_List.Value = C_Order.InvoiceRule AND InvoiceRule_AD_Ref_List.AD_Reference_ID = 150) LEFT JOIN AD_User AS SalesRep_ID_AD_User ON(SalesRep_ID_AD_User.AD_User_ID = C_Order.SalesRep_ID) LEFT JOIN C_Charge AS C_Charge_ID_C_Charge ON(C_Charge_ID_C_Charge.C_Charge_ID = C_Order.C_Charge_ID) LEFT JOIN AD_Org AS AD_OrgTrx_ID_AD_Org ON(AD_OrgTrx_ID_AD_Org.AD_Org_ID = C_Order.AD_OrgTrx_ID) LEFT JOIN C_ElementValue AS User1_ID_C_ElementValue ON(User1_ID_C_ElementValue.C_ElementValue_ID = C_Order.User1_ID) LEFT JOIN C_ElementValue AS User2_ID_C_ElementValue ON(User2_ID_C_ElementValue.C_ElementValue_ID = C_Order.User2_ID) LEFT JOIN C_ElementValue AS User3_ID_C_ElementValue ON(User3_ID_C_ElementValue.C_ElementValue_ID = C_Order.User3_ID) LEFT JOIN C_ElementValue AS User4_ID_C_ElementValue ON(User4_ID_C_ElementValue.C_ElementValue_ID = C_Order.User4_ID) LEFT JOIN AD_Ref_List AS DocStatus_AD_Ref_List ON(DocStatus_AD_Ref_List.Value = C_Order.DocStatus AND DocStatus_AD_Ref_List.AD_Reference_ID = 131) WHERE (C_Order.IsSOTrx='Y' AND EXISTS(SELECT 1 FROM C_DocType dt WHERE dt.C_DocType_ID = C_Order.C_DocTypeTarget_ID AND dt.DocBaseType = 'SOO' AND (dt.DocSubTypeSO IS NULL OR dt.DocSubTypeSO <> 'RM')) AND (C_BPartner_ID=1000313 AND (C_Order.IsSOTrx='Y' AND EXISTS(SELECT 1 FROM C_DocType dt WHERE dt.C_DocType_ID = C_Order.C_DocTypeTarget_ID AND dt.DocBaseType = 'SOO' AND (dt.DocSubTypeSO IS NULL OR dt.DocSubTypeSO <> 'RM'))))) AND C_Order.AD_Client_ID IN(0,1000000) AND C_Order.AD_Org_ID IN(0,1000000) AND (C_Order.C_Order_ID IS NULL OR C_Order.C_Order_ID NOT IN ( SELECT Record_ID FROM AD_Private_Access WHERE AD_Table_ID = 259 AND AD_User_ID <> 1001193 AND IsActive = 'Y' ))

**Comment by yamelsenih** [comment]
Please add a step by step for replicate it

**Comment by leonel1524** [comment]
1. open window business partner
2. In the 'references' section of the context menu, select sales orders corresponding to said business partner
3. When loading the window the error is generated.

**Comment by yamelsenih** [comment]
Resolved here: https://github.com/adempiere/adempiere/pull/3017
