### ISSUE TITLE
Gradle can not find ADempiere classpath

### ISSUE THREAD

**Issue by marekmosiewicz** [erpcya/adempiere-gRPC-Server#6]
I have tried to compile gRPC server (master branch) from terminal with Gradle. It seems however that Eclipse project have reference to Adempiere classpath which is not available when compiling from terminal.
I propose to add in Gradle script ADempiere jars referenced with $ADEMPIERE_HOME entry and add to documentation requirement to set $ADEMPIERE_HOME when compiling standalone Gradle

**Comment by marekmosiewicz** [comment]
In longer term I propose this project : https://github.com/marekmosiewicz/adempiere-meta .
It will download all ADempiere repositories and build it. It seems however that to use it best
I will need to create shadow core build script to make them export as artifacts.

**Comment by yamelsenih** [comment]
hi @marekmosiewicz you can see all gradle compilations here: https://travis-ci.org/github/erpcya/adempiere-gRPC-Server/builds for now is a separed project but it will be merged with adempiere

**Comment by yamelsenih** [comment]
I just add adempiere as library on dependences folder of **adempiere-gRPC-Server** project
